export const GET_FAVORITE_REQUEST: string = "GET_FAVORITE_REQUEST";
export const GET_FAVORITE_SUCCESS: string = "GET_FAVORITE_SUCCESS";
export const GET_FAVORITE_FAIL: string = "GET_FAVORITE_FAIL";

export const ADD_FAVORITE_REQUEST: string = "ADD_FAVORITE_REQUEST";
export const ADD_FAVORITE_SUCCESS: string = "ADD_FAVORITE_SUCCESS";
export const ADD_FAVORITE_FAIL: string = "ADD_FAVORITE_FAIL";

export const DELETE_FAVORITE_REQUEST: string = "DELETE_FAVORITE_REQUEST";
export const DELETE_FAVORITE_SUCCESS: string = "DELETE_FAVORITE_SUCCESS";
export const DELETE_FAVORITE_FAIL: string = "DELETE_FAVORITE_FAIL";
