export const GET_CATEGORY_LIST_REQUEST = "GET_CATEGORY_LIST_REQUEST"
export const GET_CATEGORY_LIST_SUCCESS = "GET_CATEGORY_LIST_SUCCESS"
export const GET_CATEGORY_LIST_FAIL = "GET_CATEGORY_LIST_FAIL"

export const GET_CITY_LIST_REQUEST = "GET_CITY_LIST_REQUEST"
export const GET_CITY_LIST_SUCCESS = "GET_CITY_LIST_SUCCESS"
export const GET_CITY_LIST_FAIL = "GET_CITY_LIST_FAIL"